# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(523, 453)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.367698 rgba(0, 97, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.206647 rgba(30, 178, 178, 255), stop:1 rgba(255, 255, 255, 255));\n"
"width:100%;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 70, 251, 31))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"font-size: 30px;\n"
"font-weight: 500;\n"
"font-family:\"Arial\";\n"
"color:#0000;\n"
"text-align: center;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 150, 91, 21))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"font-size: 20px;\n"
"font-family:\"Arial\";\n"
"color:#0000;\n"
"text-align: center;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 240, 121, 21))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: rgb(0, 0, 0, 0%);\n"
"background-color: qlineargradient(spread:reflect, x1:0.991, y1:1, x2:1, y2:0, stop:0.439024 rgba(0, 0, 0, 0%), stop:1 rgba(0, 0, 0, 0%));\n"
"font-size: 20px;\n"
"font-family:\"Arial\";\n"
"color:#0000;\n"
"text-align: center;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(150, 180, 231, 28))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 270, 231, 28))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 350, 140, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "SaludCul"))
        self.label_2.setText(_translate("Form", "Usuario"))
        self.label_3.setText(_translate("Form", "Contraseña"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Ingrese Su Correo"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Ingrese su Contraseña"))
        self.pushButton.setText(_translate("Form", "Iniciar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
